modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/AyOhEe/CreateEnderGateway/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/AyOhEe/CreateEnderGateway"
#logoFile="examplemod.png"
credits="Dream_m_h, slice_lmao, GalexTheStarborn, for several textures. kwaksoff, for both structures"
authors="AyOhEe"

description='''
Generates dilapidated inter-dimensional train stations, allowing Create mod trains to access the End.
'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="create"
    type="required"
    versionRange="[6.0.9,6.1.0)"
    ordering="NONE"
    side="BOTH"

[[mixin]]
    config="createendergateway.mixins.json"

[[accessTransformers]]
    file="META-INF/accesstransformer.cfg"